### ISSUE TITLE
A pod fix and a suggestion

### ISSUE THREAD

**Issue by fortesdev** [Gainsight/px-ios#4]
Hi, 
in order to make your pod accessible, please replace the following line in your podspec:
s.source = { :git => 'git@github.com:Gainsight/px-ios.git', :tag => '1.6.0' }
with:
s.source = { :git => "https://github.com/Gainsight/px-ios.git", :tag => s.version.to_s }

Also, consider that to avoid collisions with other swift frameworks or libraries, it is better not to use generic class names (ie User, Account, etc.) and apply prefixed names such as PXUser, PXAccount, etc.

**Comment by gs-apentapati** [comment]
Hey, All the Class names are prefixed with PX for Objc since swift already has namespace we did not add the prefix

will update the podspec with `s.source = { :git => "https://github.com/Gainsight/px-ios.git", :tag =>  s.version.to_s }`

**Comment by mehmoodbahria** [comment]
<img width="574" alt="Screenshot 2024-04-26 at 7 05 10 AM" src="https://github.com/Gainsight/px-ios/assets/2463158/917ad482-5a32-4356-a772-44e8a2f1d0bd">

I am getting this issue after running the "pod install" command. and the pod is added like this `( pod 'PXKit', :git => 'git@github.com:Gainsight/px-ios.git', tag: '1.11.0')` in the pod file. Kindly help me at your earliest in this.
